//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 11:32:21 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:10306/0306-ws-error-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._10306._0306_ws_error_service;
