//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 10:07:18 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://lkrnac.net/book/eiws/chapter03/ws/javaconfig/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.lkrnac.book.eiws.chapter03.ws.javaconfig.model;
