//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.30 at 11:05:35 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:10301/0301-ws-xmlconfig-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._10301._0301_ws_xmlconfig_service;
