//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 09:59:40 PM GMT 
//


package localhost._10301._0301_ws_xmlconfig_service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._10301._0301_ws_xmlconfig_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserDetialsResponse_QNAME = new QName("http://localhost:10301/0301-ws-xmlconfig-service", "UserDetialsResponse");
    private final static QName _UserRequest_QNAME = new QName("http://localhost:10301/0301-ws-xmlconfig-service", "UserRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._10301._0301_ws_xmlconfig_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserDetailsType }
     * 
     */
    public UserDetailsType createUserDetailsType() {
        return new UserDetailsType();
    }

    /**
     * Create an instance of {@link UserRequestType }
     * 
     */
    public UserRequestType createUserRequestType() {
        return new UserRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserDetailsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:10301/0301-ws-xmlconfig-service", name = "UserDetialsResponse")
    public JAXBElement<UserDetailsType> createUserDetialsResponse(UserDetailsType value) {
        return new JAXBElement<UserDetailsType>(_UserDetialsResponse_QNAME, UserDetailsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:10301/0301-ws-xmlconfig-service", name = "UserRequest")
    public JAXBElement<UserRequestType> createUserRequest(UserRequestType value) {
        return new JAXBElement<UserRequestType>(_UserRequest_QNAME, UserRequestType.class, null, value);
    }

}
