//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 11:27:43 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:10305/0305-ws-interceptor-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._10305._0305_ws_interceptor_service;
