//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 08:16:56 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "xmpp:eiws@blah.im", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._10304._0304_ws_xmpp_service;
